package com.necoarc.ityou.ui.components

/**
 * IT之家评论表情（颜文字）名称 → 远程 SVG 资源映射。
 *
 * 评论正文中的表情以方括号形式出现（例如 [坏笑]、[捂脸笑哭]）。
 * 这里维护名称到 CDN 文件名的映射，渲染时替换为内联图片。
 *
 * 数据来源：IT之家评论区前端脚本内置的表情清单（共 150 项）。
 * 资源地址：https://img.ithome.com/app/emotion/svg/rm_e_{key}.svg
 */
internal object CommentEmojiMap {

    private const val BASE_URL = "https://img.ithome.com/app/emotion/svg/rm_e_"

    /** 表情名称 → 资源 key（按名称长度降序，保证长名优先匹配）。 */
    private val NAME_TO_KEY: Map<String, String> = mapOf(
        "你看我有在笑啊" to "nikanwoyouzaixiaoa",
        "这个好这个好" to "zhegehaozhegehao",
        "弹出式摄像头" to "danchushishexiangtou",
        "超大的么么哒" to "chaodadememeda",
        "狗头不敢相信" to "goutoubuganxiangxin",
        "不正经滑稽" to "buzhengjinghuaji",
        "不好惹的鸡" to "buhaoredeji",
        "苦中作乐" to "kuzhongzuole",
        "捂脸笑哭" to "wulianxiaoku",
        "黑脸流汗" to "heilianliuhan",
        "行吧行吧" to "xingbaxingba",
        "差强人意" to "chaqiangrenyi",
        "非常惊讶" to "feichangjingya",
        "让我康康" to "rangwokangkang",
        "一本正经" to "yibenzhengjing",
        "强颜欢笑" to "qiangyanhuanxiao",
        "我挺好的" to "wotinghaode",
        "可爱滑稽" to "keaihuaji",
        "流汗滑稽" to "liuhanhuaji",
        "对眼滑稽" to "duiyanhuaji",
        "胖次滑稽" to "pangcihuaji",
        "左挖孔屏" to "zuowakongping",
        "右挖孔屏" to "youwakongping",
        "双挖孔屏" to "shuangwakongping",
        "大眼卖萌" to "dayanmaimeng",
        "暗中观察" to "anzhongguancha",
        "专业团队" to "zhuanyetuandui",
        "狗头斜眼" to "goutouxieyan",
        "考拉呆住" to "kaoladaizhu",
        "呲牙笑" to "ciyaxiao",
        "阴险笑" to "yinxianxiao",
        "六六六" to "666",
        "感兴趣" to "ganxingqu",
        "委屈哭" to "weiquku",
        "打你脸" to "danilian",
        "喷鼻血" to "penbixue",
        "流鼻血" to "liubixue",
        "擦鼻血" to "cabixue",
        "你说啥" to "nishuosha",
        "炸弹狂" to "zhadankuang",
        "原谅他" to "yuanliangta",
        "老哥稳" to "laogewen",
        "戴口罩" to "daikouzhao",
        "恰柠檬" to "qianingmeng",
        "给点吗" to "geidianma",
        "不咋行" to "buzaxing",
        "什么鬼" to "shenmegui",
        "不是吧" to "bushiba",
        "真服了" to "zhenfule",
        "滑稽鸡" to "huajiji",
        "水滴屏" to "shuidiping",
        "刘海屏" to "liuhaiping",
        "挖槽屏" to "wacaoping",
        "大边框" to "dabiankuang",
        "小恶魔" to "xiaoemo",
        "小黄鸡" to "xiaohuangji",
        "哈士奇" to "hashiqi",
        "南倒了" to "nandaole",
        "五瓣花" to "wubanhua",
        "绿帽子" to "lvmaozi",
        "柠檬精" to "ningmengjing",
        "大拇指" to "damuzhi",
        "好的呀" to "haodeya",
        "小拇指" to "xiaomuzhi",
        "微笑" to "weixiao",
        "坏笑" to "huaixiao",
        "之家" to "zhijia",
        "水库" to "shuiku",
        "发抖" to "fadou",
        "感谢" to "ganxie",
        "期待" to "qidai",
        "笑哭" to "xiaoku",
        "大哭" to "daku",
        "委屈" to "weiqu",
        "闭嘴" to "bizui",
        "挨揍" to "aizou",
        "打脸" to "dalian",
        "如花" to "ruhua",
        "害羞" to "haixiu",
        "哦吼" to "ohou",
        "可爱" to "keai",
        "流汗" to "liuhan",
        "偷看" to "toukan",
        "吃惊" to "chijing",
        "惊讶" to "jingya",
        "好的" to "haode",
        "吃瓜" to "chigua",
        "骷髅" to "kulou",
        "幽灵" to "youling",
        "摊手" to "tanshou",
        "拒绝" to "jujue",
        "嘿哈" to "heiha",
        "秃头" to "tutou",
        "庆祝" to "qingzhu",
        "再见" to "zaijian",
        "苦脸" to "kulian",
        "愤怒" to "fennu",
        "念经" to "nianjing",
        "托脸" to "tuolian",
        "潜水" to "qianshui",
        "哈欠" to "haqian",
        "睡觉" to "shuijue",
        "迷惑" to "mihuo",
        "黑脸" to "heilian",
        "佛系" to "fuxi",
        "滑稽" to "huaji",
        "相机" to "xiangji",
        "小鸡" to "xiaoji",
        "白鸡" to "baiji",
        "舔狗" to "tiangou",
        "二哈" to "erha",
        "狗头" to "goutou",
        "兔子" to "tuzi",
        "熊猫" to "xiongmao",
        "红花" to "honghua",
        "黄花" to "huanghua",
        "爱心" to "aixin",
        "菜刀" to "caidao",
        "啤酒" to "pijiu",
        "太阳" to "taiyang",
        "蛋糕" to "dangao",
        "蜡烛" to "lazhu",
        "药丸" to "yaowan",
        "菜花" to "caihua",
        "蓝花" to "lanhua",
        "铺路" to "pulu",
        "炸弹" to "zhadan",
        "手掌" to "shouzhang",
        "胜利" to "shengli",
        "拳头" to "quantou",
        "爱你" to "aini",
        "抱拳" to "baoquan",
        "握手" to "woshou",
        "比心" to "bixin",
        "酷" to "ku",
        "吐" to "tu",
        "晕" to "yun",
        "喷" to "pen",
        "衰" to "shuai",
        "色" to "se",
        "囧" to "jiong",
        "赞" to "zan",
        "嘘" to "xu",
        "烦" to "fan",
        "牛" to "niu",
        "猪" to "zhu",
        "猫" to "mao",
        "马" to "ma",
        "南" to "nan",
        "路" to "lu"
    )

    /**
     * 单个表情匹配：[名称]。
     *
     * 名称限定为 1~10 个非括号字符，避免误伤普通方括号文本。
     */
    val TOKEN_REGEX = Regex("\\[([^\\[\\]]{1,10})\\]")

    /** 将表情名称解析为完整资源 URL；非表情返回 null。 */
    fun urlFor(name: String): String? = NAME_TO_KEY[name]?.let { "$BASE_URL$it.svg" }

    /** 表情资源是否已知 */
    fun isKnown(name: String): Boolean = NAME_TO_KEY.containsKey(name)
}
